### ISSUE TITLE
Create a container from your image and test it locally

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankingSystem#21] opened 2016-11-05 22:36 UTC
**As** a developer
**I need** to create a container from the Dockerfile
**So that** I can prepare for the cloud portability

**Comment by np1535** [comment] 2016-11-13 20:15
Is this a duplicate? We already have code that builds a docker container from a docker file.

**Comment by np1535** [comment] 2016-11-14 18:30
Checked the build with the docker file; it works on bluemix too. Marking this as a duplicate of #19

**Closed** 2016-11-15 19:58 UTC
Labels: duplicate
